/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_Main */

#ifndef _Included_dev_Main
#define _Included_dev_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_Main
 * Method:    foo
 * Signature: (Ljava/io/Writer;)I
 */
JNIEXPORT jint JNICALL Java_dev_Main_foo
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
